//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by demo.rc
//
#define IDRESET                         3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DEMOTYPE                    129
#define IDB_BITMAP1                     131
#define IDD_ROTATE                      132
#define IDR_ICO1                        135
#define IDR_GIF1                        136
#define IDR_PNG1                        137
#define IDD_CAPTURE                     138
#define IDD_RESAMPLE                    139
#define IDR_TIF1                        141
#define IDM_CXIMAGE1                    142
#define IDD_DECBPP                      143
#define IDD_INCBPP                      144
#define IDD_OPTIONS                     145
#define IDD_DITHER                      147
#define IDD_THRESHOLD                   148
#define IDD_COLORIZE                    149
#define IDR_TOOLBAR1                    149
#define IDD_OPACITY                     150
#define IDD_DWNURL                      151
#define IDD_GAMMA                       152
#define IDI_OK                          152
#define IDI_CANC                        153
#define IDI_R                           154
#define IDD_HISTO                       154
#define IDI_G                           155
#define IDI_B                           156
#define IDI_GRAY                        157
#define IDD_PALETTE                     158
#define IDD_COMBINE                     159
#define IDD_FFT                         161
#define IDD_REPAIR                      162
#define IDD_DIALOG_DLT                  166
#define IDD_DIALOG_SD_DATA              167
#define IDD_DIALOG_CALIBRATION_IMAGERESIZE 168
#define IDD_DIALOG_CALIBRATION_BATCH_IMAGERESIZE 169
#define IDD_PURECOLOR                   171
#define IDD_DIALOG1                     172
#define IDD_GETIMGPOINT                 172
#define IDR_MENU_INVERSE                174
#define IDD_DIALOG_BATCH_IMAGECUT       175
#define IDD_VERIFYALGRTHM               176
#define IDC_EDIT1                       1000
#define IDC_LIST1                       1001
#define IDC_EDIT2                       1001
#define IDC_CHECK1                      1002
#define IDC_EDIT3                       1002
#define IDC_RADIO1                      1003
#define IDC_STATUS                      1003
#define IDC_EDIT4                       1003
#define IDC_CHECK3                      1003
#define IDC_RADIO2                      1004
#define IDC_URL                         1004
#define IDC_EDIT5                       1004
#define IDC_CHECK4                      1004
#define IDC_RADIO3                      1005
#define IDC_EDIT10                      1005
#define IDC_RADIO4                      1006
#define IDC_LOG                         1006
#define IDC_LOAD                        1006
#define IDC_RADS                        1006
#define IDC_RADIO5                      1007
#define IDC_SAVE                        1007
#define IDC_light_ratio                 1007
#define IDC_RADI                        1007
#define IDC_CHECK2                      1008
#define IDC_RADE                        1008
#define IDC_BAR                         1009
#define IDC_NOISES                      1009
#define IDC_COMBO1                      1010
#define IDC_NOISEI                      1010
#define IDC_COMBO2                      1011
#define IDC_NOISEE                      1011
#define IDC_COMBO3                      1012
#define IDC_COMBO4                      1013
#define IDC_COMBO5                      1014
#define IDC_REAL                        1015
#define IDC_COMBO9                      1015
#define IDC_IMAG                        1016
#define IDC_COMBO6                      1018
#define IDC_COMBO7                      1019
#define IDC_COMBO8                      1020
#define IDC_BUTTON_CTRL_DLG             1022
#define IDC_BUTTON_IMG_DLG              1023
#define IDC_EDIT_CTRLPT_FILE            1024
#define IDC_EDIT_FILE_IMG               1025
#define ID_CANCEL                       1026
#define IDC_EDIT_x                      1027
#define IDC_EDIT_y                      1028
#define IDC_EDIT_Z                      1029
#define IDC_CALIBRATION_IMAGERESIZE_HEIGHT 1030
#define IDC_CALIBRATION_IMAGERESIZE_WIDTH 1031
#define IDC_BUTTON_CALIBRATION_LOADBATCHIMG 1032
#define IDC_EDIT_CALIBRATION_BATCHIMG_WIDTH 1033
#define IDC_EDIT_CALIBRATION_BATCHIMG_HEIGHT 1034
#define ID_BUTTON_CALIBRATION_BATCHIMG_CONVERT 1036
#define IDC_SLIDER1                     1037
#define IDC_SLIDER2                     1038
#define IDC_SLIDER3                     1039
#define IDC_PURECOLOR_RED               1040
#define IDC_PURECOLOR_GREEN             1041
#define IDC_PURECOLOR_BLUE              1042
#define IDC_RED_POS                     1046
#define IDC_GREEN_POS                   1047
#define IDC_BLUE_POS                    1048
#define IDC_EDIT6                       1051
#define IDC_EDIT7                       1052
#define IDC_EDIT8                       1053
#define IDC_EDIT9                       1054
#define IDC_light_x                     1055
#define IDC_EDIT_LEFT_BOUNDARY          1055
#define IDC_light_y                     1056
#define IDC_EDIT_RIGHT_BOUNDARY         1056
#define IDC_light_z                     1057
#define IDC_EDIT_TOP_BOUNDARY           1057
#define IDC_EDIT_BOTTOM_BOUNDARY        1058
#define ID_START_CUT                    1059
#define IDC_BUTTON_LOAD_IMAGES          1060
#define ID_OK                           1061
#define IDC_IMAGE_ZONE                  1063
#define IDC_THETAS                      1064
#define IDC_THETAI                      1065
#define IDC_THETAE                      1066
#define IDC_PHIS                        1067
#define IDC_PHII                        1068
#define IDC_PHIE                        1069
#define ID_STRETCH_MODE                 32771
#define ID_TRANSFORM_ELLIPSE            32772
#define ID_IMAGE_FROM_BITMAP            32773
#define ID_CXIMAGE_MIRROR               32774
#define ID_CXIMAGE_FLIP                 32775
#define ID_WINDOW_DUPLICATE             32776
#define ID_CXIMAGE_NEGATIVE             32777
#define ID_CXIMAGE_GRAYSCALE            32778
#define ID_CXIMAGE_ROTATE               32779
#define ID_CXIMAGE_LOADJPEGRESOURCE     32780
#define ID_CXIMAGE_LOADICONRESOURCE     32781
#define ID_CXIMAGE_LOADGIFRESOURCE      32782
#define ID_CXIMAGE_LOADPNGRESOURCE      32783
#define ID_VIEW_ZOOMIN                  32786
#define ID_VIEW_ZOOMOUT                 32787
#define ID_VIEW_NORMALVIEWING11         32788
#define ID_FILE_CAPTURE                 32789
#define ID_CXIMAGE_LOADTIFRESOURCE      32790
#define ID_WINDOW_CLOSEALL              32791
#define ID_CXIMAGE_SETTRANSPARENCY      32792
#define ID_CXIMAGE_REMOVETRANSPARENCY   32793
#define ID_CXIMAGE_RESAMPLE             32794
#define ID_CXIMAGE_DECREASEBPP          32795
#define ID_CXIMAGE_INCREASEBPP          32796
#define ID_CXIMAGE_OPTIONS              32797
#define ID_CXIMAGE_DITHER               32798
#define ID_CXIMAGE_THRESHOLD            32799
#define ID_CXIMAGE_SPLITRGB             32800
#define ID_CXIMAGE_SPLITYUV             32801
#define ID_CXIMAGE_SPLITHSL             32802
#define ID_CXIMAGE_PSEUDOCOLORS         32803
#define ID_CXIMAGE_SPLITCHANNELS        32804
#define ID_CXIMAGE_RESOURCES            32805
#define ID_CXIMAGE_COLORIZE             32808
#define ID_CXIMAGE_LIGHTEN              32809
#define ID_CXIMAGE_DARKEN               32810
#define ID_CXIMAGE_CONTRAST             32811
#define ID_CXIMAGE_EMBOSS               32812
#define ID_CXIMAGE_BLUR                 32813
#define ID_CXIMAGE_SOFTEN               32814
#define ID_CXIMAGE_SHARPEN              32815
#define ID_CXIMAGE_EDGE                 32816
#define ID_CXIMAGE_ERODE                32817
#define ID_CXIMAGE_DILATE               32818
#define ID_FILE_SELECTSOURCE            32824
#define ID_FILE_ACQUIRE                 32825
#define ID_BUTTON32842                  32842
#define ID_VIEW_MENUSTYLE_NORMAL        32846
#define ID_VIEW_MENUSTYLE_XP            32847
#define ID_CXIMAGE_CROP                 32848
#define ID_CXIMAGE_REMOVEALPHACHANNEL   32850
#define ID_CXIMAGE_OPACITY              32851
#define ID_CXIMAGE_INVETALPHA           32852
#define ID_CXIMAGE_ALPHAPALETTETOGGLE   32853
#define ID_CXIMAGE_ALPHASTRIP           32854
#define ID_CXIMAGE_ROTATEL              32855
#define ID_CXIMAGE_ROTATER              32856
#define ID_CXIMAGE_DEMOSAVEMULTIPAGETIFF 32857
#define ID_CXIMAGE_DEMOSAVEANIMATEDGIF  32861
#define ID_CXIMAGE_DOWNLOADFROMURL      32862
#define ID_CXIMAGE_GAMMA                32863
#define ID_CXIMAGE_MEDIAN               32864
#define ID_CXIMAGE_ADDNOISE             32865
#define ID_VIEW_TOOLS_MOVE              32869
#define ID_VIEW_TOOLS_SELECT            32871
#define ID_VIEW_FULLSCREEN              32872
#define ID_VIEW_TOOLS_ZOOM              32874
#define ID_VIEW_HISTOGRAM               32876
#define ID_VIEW_PALETTE                 32877
#define ID_CXIMAGE_COMBINE              32879
#define ID_CXIMAGE_FFT                  32880
#define ID_CXIMAGE_SPLITYIQ             32881
#define ID_CXIMAGE_SPLITXYZ             32882
#define ID_CXIMAGE_REPAIR               32883
#define ID_FILTERS_SPLIT                32884
#define ID_IMGPOINT_NUM1                32885
#define ID_IMGPOINT_NUM2                32886
#define ID_IMGPOINT_NUM3                32887
#define ID_IMGPOINT_NUM4                32888
#define ID_IMGPOINT_NUM5                32889
#define ID_IMGPOINT_NUM7                32891
#define ID_IMGPOINT_NUM8                32892
#define ID_IMGPOINT_NUM6                32893
#define ID_IMGPOINT_SAVE                32894
#define ID_IMGPOINT_LOADCTRLPNT         32896
#define ID_IMGPOINT_COMPUTE_HT          32897
#define ID_IMGPOINT_STATUSHEHE          32898
#define ID_CALIBRATION_LOADCAMPARA      32899
#define ID_CALIBRATION_INPUTGRDPOS      32900
#define ID_MENUITEM32901                32901
#define ID_MENUITEM32902                32902
#define ID_CALIBRATION_IMAGERESIZE      32903
#define ID_CALIBRATION_BATCH_IMAGERESIZE 32904
#define ID_TEST_SAVE                    32905
#define ID_CALIBRATION_FLOODFILL_TEST   32906
#define ID_CONCENTRIC_CENTER            32907
#define ID_CONCENTRIC_CIRCLE            32908
#define ID_ADJUST                       32910
#define ID_DRAWBACK                     32911
#define ID_IMGPOINT_COMPUTE_HT_CONCENTERIC 32912
#define ID_CALIB_CONVERT_PURECOLOR      32913
#define ID_COMPUTE_ERROR                32914
#define ID_COMPUTE_CMR_PAR              32918
#define ID_IMPORT_LIGHT_POINT           32919
#define ID_INVERSE_BY_X                 32920
#define ID_INVERSE_BY_Y                 32921
#define ID_SAVE_INVERSE_IMAGE           32922
#define ID_CPMPUTE_VIRTUAL_CAMERA       32923
#define ID_CALIBRATION_BATCH_IMAGECUT   32924
#define ID_VERIFY_ALGORITHM             32928
#define ID_INDICATOR1                   59142
#define ID_INDICATOR2                   59143
#define ID_INDICATOR3                   59144
#define ID_IMGPOINT_RESET               59145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        177
#define _APS_NEXT_COMMAND_VALUE         32930
#define _APS_NEXT_CONTROL_VALUE         1070
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
